// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP1Asp.Data;

#nullable disable

namespace TP1Asp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230906120424_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TP1Asp.Models.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc");

                    b.Property<string>("TitleTask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titre_task");

                    b.HasKey("Id");

                    b.ToTable("todolist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Cuisiner du poulet aux olives",
                            TitleTask = "Faire à manger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
